version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "socially-serverless-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-w7fazjv91dr3"
s3_prefix = "socially-serverless-api"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
